import C from "../Assets/TechIcons/C++.svg";
import Git from "../Assets/TechIcons/Git.svg";
import Java from "../Assets/TechIcons/Java.svg";
import { SiNextdotjs } from "react-icons/si";
import Javascript from "../Assets/TechIcons/Javascript.svg";
import Mongo from "../Assets/TechIcons/Mongo.svg";
import MUI from "../Assets/TechIcons/MUI.svg";
import Next from "../Assets/TechIcons/Next.svg";
import Node from "../Assets/TechIcons/Node.svg";
import Postman from "../Assets/TechIcons/Postman.svg";
import Python from "../Assets/TechIcons/Python.svg";
import ReactIcon from "../Assets/TechIcons/React.svg";
import Redux from "../Assets/TechIcons/Redux.svg";
import SQL from "../Assets/TechIcons/SQL.svg";
import Tailwind from "../Assets/TechIcons/Tailwind.svg";
import Typescript from "../Assets/TechIcons/Typescript.svg";
import brave from "../Assets/TechIcons/brave-browser-icon.webp";
import macOs from "../Assets/TechIcons/mac-os.png";
import slack from "../Assets/TechIcons/slack.png";
import trello from "../Assets/TechIcons/trello.png";
import vsCode from "../Assets/TechIcons/vscode.svg";
import {
  SiAdobe,
  SiAlibabacloud,
  SiAlpinedotjs,
  SiAmazonaws,
  SiAntdesign,
  SiApache,
  SiBootstrap,
  SiBun,
  SiC,
  SiCsharp,
  SiCplusplus,
  SiCanva,
  SiChartdotjs,
  SiCloudflare,
  SiCss3,
  SiDaisyui,
  SiDart,
  SiDocker,
  SiE,
  SiEsbuild,
  SiExpo,
  SiExpress,
  SiFigma,
  SiFirebase,
  SiFlutter,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGitlab,
  SiGooglecloud,
  SiGraphql,
  SiHtml5,
  SiJira,
  SiJquery,
  SiJsonwebtokens,
  SiMarkdown,
  SiMicrosoftazure,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNetlify,
  SiNginx,
  SiNodedotjs,
  SiNodemon,
  SiNotion,
  SiNpm,
  SiNuxtdotjs,
  SiOracle,
  SiPnpm,
  SiPostgresql,
  SiPowershell,
  SiPrisma,
  SiReact,
  SiReacthookform,
  SiReactquery,
  SiReactrouter,
  SiRedux,
  SiRender,
  SiSass,
  SiSlack,
  SiSqlite,
  SiStyledcomponents,
  SiSupabase,
  SiTailwindcss,
  SiThreedotjs,
  SiTrello,
  SiTypescript,
  SiVercel,
  SiVite,
  SiWeb3Dotjs,
  SiWordpress,
} from "react-icons/si";

export type SkillItem = {
  label: string;
  alt: string;
  image?: string;
  iconText?: string;
  icon?: typeof SiReact;
};

export const TECH_ITEMS = [
  { label: "C", alt: "C", icon: SiC },
  { label: "C#", alt: "C sharp", icon: SiCsharp },
  { label: "C++", image: C.src, alt: "C++" },
  { label: "Java", image: Java.src, alt: "Java" },
  { label: "Python", image: Python.src, alt: "Python" },
  { label: "Dart", alt: "Dart", icon: SiDart },
  { label: "JavaScript", image: Javascript.src, alt: "JavaScript" },
  { label: "TypeScript", image: Typescript.src, alt: "TypeScript" },
  { label: "HTML5", alt: "HTML5", icon: SiHtml5 },
  { label: "CSS3", alt: "CSS3", icon: SiCss3 },
  { label: "Markdown", alt: "Markdown", icon: SiMarkdown },
  { label: "React", image: ReactIcon.src, alt: "React" },
  { label: "React Native", alt: "React Native", icon: SiReact },
  { label: "React Query", alt: "React Query", icon: SiReactquery },
  { label: "React Router", alt: "React Router", icon: SiReactrouter },
  { label: "React Hook Form", alt: "React Hook Form", icon: SiReacthookform },
  { label: "Next.js", image: Next.src, alt: "Next.js", icon: SiNextdotjs },
  { label: "Nuxt.js", alt: "Nuxt.js", icon: SiNuxtdotjs },
  { label: "Node.js", image: Node.src, alt: "Node.js" },
  { label: "Nodemon", alt: "Nodemon", icon: SiNodemon },
  { label: "Express.js", alt: "Express.js", icon: SiExpress },
  { label: "NestJS", alt: "NestJS", icon: SiNestjs },
  { label: "Flutter", alt: "Flutter", icon: SiFlutter },
  { label: "Expo", alt: "Expo", icon: SiExpo },
  { label: "Alpine.js", alt: "Alpine.js", icon: SiAlpinedotjs },
  { label: "Redux", image: Redux.src, alt: "Redux" },
  { label: "GraphQL", alt: "GraphQL", icon: SiGraphql },
  { label: "Tailwind CSS", image: Tailwind.src, alt: "Tailwind CSS" },
  { label: "Bootstrap", alt: "Bootstrap", icon: SiBootstrap },
  { label: "DaisyUI", alt: "DaisyUI", icon: SiDaisyui },
  { label: "Material UI", image: MUI.src, alt: "Material UI" },
  { label: "Ant Design", alt: "Ant Design", icon: SiAntdesign },
  { label: "Sass", alt: "Sass", icon: SiSass },
  { label: "Styled Components", alt: "Styled Components", icon: SiStyledcomponents },
  { label: "Radix UI", alt: "Radix UI", iconText: "Rx" },
  { label: "EJS", alt: "EJS", icon: SiE },
  { label: "Vite", alt: "Vite", icon: SiVite },
  { label: "Esbuild", alt: "Esbuild", icon: SiEsbuild },
  { label: "jQuery", alt: "jQuery", icon: SiJquery },
  { label: "MongoDB", image: Mongo.src, alt: "MongoDB", icon: SiMongodb },
  { label: "PostgreSQL", image: SQL.src, alt: "PostgreSQL", icon: SiPostgresql },
  { label: "MySQL", alt: "MySQL", icon: SiMysql },
  { label: "SQLite", alt: "SQLite", icon: SiSqlite },
  { label: "Firebase", alt: "Firebase", icon: SiFirebase },
  { label: "Supabase", alt: "Supabase", icon: SiSupabase },
  { label: "Prisma", alt: "Prisma", icon: SiPrisma },
  { label: "Chart.js", alt: "Chart.js", icon: SiChartdotjs },
  { label: "Three.js", alt: "Three.js", icon: SiThreedotjs },
  { label: "Web3.js", alt: "Web3.js", icon: SiWeb3Dotjs },
  { label: "JWT", alt: "JSON Web Tokens", icon: SiJsonwebtokens },
  { label: "WordPress", alt: "WordPress", icon: SiWordpress },
  { label: "Gutenberg", alt: "Gutenberg", iconText: "Gu" },
  { label: ".NET", alt: ".NET", iconText: ".N" },
  { label: "PHP", alt: "PHP", iconText: "PHP" },
];

export const TOOL_ITEMS: SkillItem[] = [
  { label: "Git", image: Git.src, alt: "Git", icon: SiGit },
  { label: "GitHub", alt: "GitHub", icon: SiGithub },
  { label: "GitLab", alt: "GitLab", icon: SiGitlab },
  { label: "GitHub Actions", alt: "GitHub Actions", icon: SiGithubactions },
  { label: "VS Code", image: vsCode.src, alt: "VS Code" },
  { label: "Postman", image: Postman.src, alt: "Postman" },
  { label: "NPM", alt: "NPM", icon: SiNpm },
  { label: "PNPM", alt: "PNPM", icon: SiPnpm },
  { label: "Bun", alt: "Bun", icon: SiBun },
  { label: "Bash", alt: "Bash", iconText: "$_" },
  { label: "PowerShell", alt: "PowerShell", icon: SiPowershell },
  { label: "Mac Os", image: macOs.src, alt: "macOs" },
  { label: "Brave Browser", image: brave.src, alt: "Brave" },
  { label: "Trello", image: trello.src, alt: "trello" },
  { label: "Slack", image: slack.src, alt: "slack" },
  { label: "Notion", alt: "Notion", icon: SiNotion },
  { label: "Jira", alt: "Jira", icon: SiJira },
  { label: "Figma", alt: "Figma", icon: SiFigma },
  { label: "Canva", alt: "Canva", icon: SiCanva },
  { label: "Adobe", alt: "Adobe", icon: SiAdobe },
  { label: "Photoshop", alt: "Adobe Photoshop", iconText: "Ps" },
  { label: "Docker", alt: "Docker", icon: SiDocker },
  { label: "Apache", alt: "Apache", icon: SiApache },
  { label: "Nginx", alt: "Nginx", icon: SiNginx },
  { label: "Vercel", alt: "Vercel", icon: SiVercel },
  { label: "Netlify", alt: "Netlify", icon: SiNetlify },
  { label: "Render", alt: "Render", icon: SiRender },
  { label: "Cloudflare", alt: "Cloudflare", icon: SiCloudflare },
  { label: "AWS", alt: "AWS", icon: SiAmazonaws },
  { label: "Azure", alt: "Microsoft Azure", icon: SiMicrosoftazure },
  { label: "Google Cloud", alt: "Google Cloud", icon: SiGooglecloud },
  { label: "Oracle Cloud", alt: "Oracle Cloud", icon: SiOracle },
  { label: "Alibaba Cloud", alt: "Alibaba Cloud", icon: SiAlibabacloud },
];

export const SKILL_BRAND_COLORS: Record<string, string> = {
  C: "#A8B9CC",
  "C#": "#68217A",
  "C++": "#00599C",
  Java: "#ED8B00",
  Python: "#3776AB",
  Dart: "#0175C2",
  JavaScript: "#F7DF1E",
  TypeScript: "#3178C6",
  HTML5: "#E34F26",
  CSS3: "#1572B6",
  Markdown: "#FFFFFF",
  React: "#61DAFB",
  "React Native": "#61DAFB",
  "React Query": "#FF4154",
  "React Router": "#CA4245",
  "React Hook Form": "#EC5990",
  "Next.js": "#FFFFFF",
  "Nuxt.js": "#00DC82",
  "Node.js": "#68A063",
  Nodemon: "#76D04B",
  "Express.js": "#FFFFFF",
  NestJS: "#E0234E",
  Flutter: "#02569B",
  Expo: "#FFFFFF",
  "Alpine.js": "#8BC0D0",
  Redux: "#764ABC",
  GraphQL: "#E10098",
  "Tailwind CSS": "#38BDF8",
  Bootstrap: "#7952B3",
  DaisyUI: "#5A0EF8",
  "Material UI": "#007FFF",
  "Ant Design": "#1677FF",
  Sass: "#CC6699",
  "Styled Components": "#DB7093",
  "Radix UI": "#FFFFFF",
  EJS: "#B4CA65",
  Vite: "#646CFF",
  Esbuild: "#FFCF00",
  jQuery: "#0769AD",
  MongoDB: "#47A248",
  PostgreSQL: "#4169E1",
  MySQL: "#4479A1",
  SQLite: "#003B57",
  Firebase: "#FFCA28",
  Supabase: "#3ECF8E",
  Prisma: "#5A67D8",
  "Chart.js": "#FF6384",
  "Three.js": "#FFFFFF",
  "Web3.js": "#F16822",
  JWT: "#FFFFFF",
  WordPress: "#117AC9",
  Gutenberg: "#077CB2",
  ".NET": "#512BD4",
  PHP: "#777BB4",
  Git: "#F05032",
  GitHub: "#FFFFFF",
  GitLab: "#FC6D26",
  "GitHub Actions": "#2088FF",
  "VS Code": "#007ACC",
  Postman: "#FF6C37",
  NPM: "#CB3837",
  PNPM: "#F69220",
  Bun: "#FFFFFF",
  Bash: "#4EAA25",
  PowerShell: "#5391FE",
  "Mac Os": "#FFFFFF",
  "Brave Browser": "#FB542B",
  Trello: "#0C66E4",
  Slack: "#36C5F0",
  Notion: "#FFFFFF",
  Jira: "#2684FF",
  Figma: "#F24E1E",
  Canva: "#00C4CC",
  Adobe: "#FF0000",
  Photoshop: "#31A8FF",
  Docker: "#2496ED",
  Apache: "#D22128",
  Nginx: "#009639",
  Vercel: "#FFFFFF",
  Netlify: "#00C7B7",
  Render: "#46E3B7",
  Cloudflare: "#F38020",
  AWS: "#FF9900",
  Azure: "#0078D4",
  "Google Cloud": "#4285F4",
  "Oracle Cloud": "#F80000",
  "Alibaba Cloud": "#FF6701",
};

export const SKILL_CARD_CLASS =
  "group flex min-h-32 flex-col items-center justify-center gap-3 rounded-[1.15rem] border border-white/10 bg-white/[0.055] p-4 text-center shadow-2xl shadow-black/10 backdrop-blur-xl transition duration-300 hover:-translate-y-1 hover:shadow-glow";

export const SKILL_IMAGE_CLASS =
  "h-10 w-10 object-contain transition group-hover:scale-110";

export const SKILL_TEXT_CLASS = "text-sm font-bold text-white/75";
